# Generated by Django 3.2.4 on 2021-06-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('primary', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='No Log Message')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ('primary',),
            },
        ),
    ]
