# Generated by Django 3.2 on 2021-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sclass', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('grades', models.ManyToManyField(to='student.Grades')),
            ],
        ),
    ]
