# Generated by Django 3.2.3 on 2021-05-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('sclass', models.CharField(max_length=100)),
                ('avg', models.FloatField(default=0.0)),
                ('m1', models.CharField(max_length=100)),
                ('d1', models.FloatField()),
                ('m2', models.CharField(max_length=100)),
                ('d2', models.FloatField()),
                ('m3', models.CharField(max_length=100)),
                ('d3', models.FloatField()),
                ('m4', models.CharField(max_length=100)),
                ('d4', models.FloatField()),
                ('m5', models.CharField(max_length=100)),
                ('d5', models.FloatField()),
                ('m6', models.CharField(max_length=100)),
                ('d6', models.FloatField()),
                ('m7', models.CharField(max_length=100)),
                ('d7', models.FloatField()),
            ],
        ),
    ]
