# Generated by Django 3.2 on 2021-05-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avg',
        ),
    ]
