# Generated by Django 3.2 on 2021-05-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avg',
            field=models.FloatField(default=0.0),
        ),
    ]
